sudo: false

language: node_js

dist:
  trusty

node_js:
  - '10'
  - '9'
  - '8'
  - '6'

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
      - gcc-5
      - libgtk-3-dev
      - xvfb
      - at-spi2-core

os:
  - osx
  - linux
  - windows

before_install:
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew update         ; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew upgrade python ; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then pip3 install click pyobjc-framework-Quartz; fi
  - if [ "$TRAVIS_OS_NAME" == "windows" ]; then choco install python2 -y; fi

install:
  - if [ "$TRAVIS_OS_NAME" == "linux"   ]; then export CC="gcc-5"                               ; fi
  - if [ "$TRAVIS_OS_NAME" != "windows" ]; then export DISPLAY=':99.0'                          ; fi
  - if [ "$TRAVIS_OS_NAME" != "windows" ]; then Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 & fi
  - npm install
